pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('bigdata-ml-lab1')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage('Login') {
            steps {
                    //withCredentials([usernamePassword(credentialsId: 'mle-template', passwordVariable: 'DOCKER_REGISTRY_PWD', usernameVariable: 'DOCKER_REGISTRY_USER')]){
                    //bat 'chcp 65001 && echo %DOCKER_REGISTRY_PWD% | docker login -u %DOCKER_REGISTRY_USER% --password-stdin'}
                    //bat 'chcp 65001 && echo %DOCKERHUB_CREDS_PSW% | docker login -u %DOCKERHUB_CREDS_USR% --password-stdin'
                    bat 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }

        stage('Pull image') {
            steps {
                bat '''
                    docker pull zarus03/ml-big-data-lab-1:latest
                '''
            }
        }

        stage('Run container') {
            steps {
                bat '''
                    docker run --name ml-big-data-lab-1 -p 80:5556 -d zarus03/ml-big-data-lab-1:latest
                '''
            }
        }
	}

    post {
        always {
            bat 'docker stop ml-big-data-lab-1 && docker logout'
        }
    }
}
